services:
  - type: web
    name: my-calculator-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
